### ISSUE TITLE
Last color without semicolon breaks next classname renaming

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#13]
I use `rename-css-selectors` after webpack with postss (and [csswring)](https://github.com/hail2u/node-csswring) have finished their work.

So css goes to rcs-core in minify state, without last semicolon inside class body. And seems like it breaks renaming.

Here is minimal example:
```css
.link{background:#616060}.tag{display:flex}
```
is transformed into
```css
.t{background:#616060}.tag{display:flex}
```
