### ISSUE TITLE
Replacing @keyframes name doesn't replace animation name

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#15]
With new `replaceKeyframes: true` option, this code
```css
@keyframes Spinner_rotate_21ZiX{
  0%{
    transform:rotate(0deg);
  }
  100%{
    transform:rotate(360deg);
  }
}
.Spinner_spinner_LszC2{
  animation:Spinner_rotate_21ZiX 1.1s infinite linear;
}
```
is transformed into
```css
@keyframes t{
  0%{
    transform:rotate(0deg);
  }
  100%{
    transform:rotate(360deg);
  }
}
.n{
  animation:Spinner_rotate_21ZiX 1.1s infinite linear;
}
```
