### ISSUE TITLE
Last color without semicolon breaks next classname renaming 2

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#16]
Related to https://github.com/JPeer264/node-rcs-core/issues/13 : )
But now if last property value without semicolon ends with `rem`
```css
.ToolBar{padding:0 .357143rem}.ToolBar_selected{color:#0f705d}
```
==>
```css
.t{padding:0 .357143rem}.t_selected{color:#0f705d}
```

Or such media query
```css
@media(max-width:480px){.AttributeList{display:block}.Header{display:table}}
```
==>
```css
@media(max-width:480px){.AttributeList{display:block}.t{display:table}}
```

`rcs-core` version `0.9.1`
