### ISSUE TITLE
Triggers selectors in CSS block 

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-rcs-core#2]
Related: [node-rename-css-selectors#2](https://github.com/JPeer264/node-rename-css-selectors/issues/2)
Trigger classes which are actually no classes.

```css
.my-class {
    filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
}
```

will trigger the classes:

`.my-class`, `.Microsoft` and `.gradient(`.

Fix: Do not trigger selectors within blocks
