### ISSUE TITLE
Replacing attribute-selectors in a smart way

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-rcs-core#36]
As mentioned in https://github.com/JPeer264/node-rcs-core/issues/33#issuecomment-384650054 it should be possible to prefix/suffix out the attribute selectors to achieve smaller selectors which are selectable by attribute selectors.

Example before:
```css
.select-a-long-name, .select-another-name {
  margin-left: 10px;
}
.board > [class^=select-] {
  padding: 0;
}
```

After
```css
.selecta, .selectb {
  ...
}
.a > [class^=select] {
  ...
}
```
