### ISSUE TITLE
The order of parsing CSS file breaks the renaming

### ISSUE THREAD

**Issue by X-Ryl669** [JPeer264/node-rcs-core#96]
Ok, this is a more complex issue.
To simplify, let's say you have 2 CSS files containing:
**B.css**
```css
.i-icon:before { color: red; }
```
**A.css**
```css
[class^="i-"]:before {
  font: myfont;
}

.i-icon:before {
   content: '\f101';
}
.i-file:before {
   content: '\f102';
}
```
If `B.css` is parsed first, then the selector `.i-icon` will be mapped to `.a`.
If `A.css` is parsed first, then the selector `.i-icon` will be (correctly) mapped to `.i-a` (because of the attribute selector above).

In the former case, all the rules in the attribute selector are ignored, and this is a bug.
